version: '3'
services:
  dev_mysql:
    image: mysql/mysql-server:5.7
    expose:
      - 3306
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=microblog
      - MYSQL_USER=microblog
      - MYSQL_PASSWORD=345345
  prod:
      image: jerra/microblog:latest
    links:
      - dev_mysql
    environment:
      - SECRET_KEY=my-secret-key
      - DATABASE_URL=mysql+pymysql://microblog:345345@dev_mysql/microblog
    ports:
      - 8000:5000
    restart: always
  test_mysql:
    image: mysql/mysql-server:5.7
    expose:
      - 3306
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=microblog
      - MYSQL_USER=microblog
      - MYSQL_PASSWORD=345345
  test:
    build:
      context: .
      dockerfile: ./docker/Dockerfile_test
    links:
      - test_mysql
    environment:
      - SECRET_KEY=my-secret-key
      - DATABASE_URL=mysql+pymysql://microblog:345345@test_mysql/microblog
